jamal = {
    "character": {"1": "1", "2": "2", "3": "3", "4": "4"},
    "emotion": {
        "1": "happy",
        "2": "sad",
        "3": "angry",
        "4": "bore",
        "5": "content",
        "6": "glare",
        "7": "sarcasm",
        "8": "worried",
    },
    "intensity": {"1": True, "2": False},
    "head_direction": {"1": "L", "2": "M", "3": "R"},
    "eyes_direction": {"1": "L", "2": "M", "3": "R"},
    "screen_mode": {
        "1": "office",
        "2": "explaination",
        "3": "white",
        "4": "plain",
    },
    "body_action": {
        "1": "achieve",
        "2": "answer",
        "3": "explain",
        "4": "me",
        "5": "not_me",
        "6": "question",
        "7": "technical",
        "8": "why",
        "9": "you",
    },
    "reaction": {
        "1": "happy",
        "2": "sad",
        "3": "angry",
        "4": "bore",
        "5": "content",
        "6": "glare",
        "7": "scard",
        "8": "worried",
    },
}

kamal = {
    "character": {
        "1": "1",
        "2": "2",
        "3": "3",
        "4": "4",
        "5": "5",
        "6": "6",
        "7": "7",
        "8": "8",
        "9": "9",
        "10": "10",
    },
    "emotion": {
        "1": "happy",
        "2": "sad",
        "3": "angry",
        "4": "bore",
        "5": "content",
        "6": "glare",
        "7": "sarcasm",
        "8": "worried",
        "9": "crazy",
        "10": "evil_laugh",
        "11": "lust",
        "12": "shock",
        "13": "silly",
        "14": "spoked",
    },
    "intensity": {"1": True, "2": False},
    "head_direction": {"1": "L", "2": "M", "3": "R"},
    "eyes_direction": {"1": "L", "2": "M", "3": "R"},
    "screen_mode": {
        "1": "office",
        "2": "explaination",
        "3": "white",
        "4": "plain",
        "5": "green",
    },
    "body_action": {
        "1": "achieve",
        "2": "answer",
        "3": "explain",
        "4": "me",
        "5": "not_me",
        "6": "question",
        "7": "technical",
        "8": "why",
        "9": "achieve",
        "10": "answer",
        "11": "chilling",
        "12": "come",
        "13": "confuse",
        "14": "crazy",
        "15": "dancing",
        "16": "explain",
        "17": "feeling_down",
        "18": "hi",
        "19": "i",
        "20": "idea",
        "21": "idk",
        "22": "joy",
        "23": "jumping",
        "24": "kung_fu",
        "25": "love",
        "27": "meditation",
        "28": "model",
        "30": "paper",
        "31": "praying",
        "32": "question",
        "33": "running",
        "34": "search",
        "35": "shy",
        "36": "singing",
        "37": "sneaky",
        "38": "standing",
        "39": "technical",
        "40": "that",
        "41": "thinking",
        "42": "this",
        "43": "what",
        "44": "why",
        "45": "winner",
        "46": "yeah",
        "47": "you",
    },
    "reaction": {
        "1": "happy",
        "2": "sad",
        "3": "angry",
        "4": "bore",
        "5": "content",
        "6": "glare",
        "7": "scard",
        "8": "worried",
    },
}

actions = {"jamal": jamal, "kamal": kamal}
